/// Flutter icons WIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WIcons
///      fonts:
///       - asset: fonts/WIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WIcons {
  WIcons._();

  static const _kFontFam = 'WIcons';

  static const IconData cloudy = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData crescent = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData cyclone = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData dawn = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData eclipse = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData farenheit = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData hail = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData haze = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData heat = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData high_temperature = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData humidity = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData lighting = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData low_temperature = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData moon_phase = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData moon = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData night = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData pressure = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData rain = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData rainbow = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData raindrop = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData snow = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData snow2 = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData snowy = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData storm = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData sun = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData sunset = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData temperature = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData thermometer = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData thunder = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData thunderstorm = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData tornado = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData umbrella = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData weather = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData weathercock = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData wind = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData windsock = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData windy = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData antenna = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData celsius = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData cloud = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData clouds = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData cloudy_day = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData cloudy_night = const IconData(0xe82c, fontFamily: _kFontFam);
}
